# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arraypermer <- function(x, dims, perm) {
    .Call(`_rutabaga_arraypermer`, x, dims, perm)
}

collapser <- function(x, dims, keep) {
    .Call(`_rutabaga_collapser`, x, dims, keep)
}

vec_sum <- function(x, y, a) {
    .Call(`_rutabaga_vec_sum`, x, y, a)
}

